import Link from "next/link";
import { FashionPlaceholder } from "@/components/fashion-placeholder";
import { CatalogCard } from "@/components/catalog-card";
import { products } from "@/lib/catalog";
const categories = [{name:"Kurtas",slug:"kurtas",tone:"rose"},{name:"Kurta Sets",slug:"kurta-sets",tone:"olive"},{name:"Dresses",slug:"dresses",tone:"blue"},{name:"Sarees",slug:"sarees",tone:"clay"},{name:"Lehengas",slug:"lehengas",tone:"plum"},{name:"Suits",slug:"suits",tone:"sand"}] as const;
const occasions = [{name:"Workwear",tone:"blue"},{name:"Festive",tone:"clay"},{name:"Wedding",tone:"plum"},{name:"Casual",tone:"olive"}] as const;
const featured = [products[0],products[7],products[20],products[31]];
export default function Home() {return <main id="main-content">
<section className="hero"><div className="hero-content"><span className="eyebrow">AURELIA · A new perspective</span><h1 className="serif">Wear the<br/>moment.</h1><p>Modern Indian dressing with room for every version of you. Explore our first edit of original fashion concepts.</p><div className="hero-actions"><Link className="button" href="/shop">Explore the edit</Link><a className="button button-outline" href="#categories">Discover styles</a></div></div><FashionPlaceholder label="Editorial campaign concept artwork" tone="clay"/></section>
<section id="categories" className="section container"><div className="section-heading"><div><span className="eyebrow">Find your silhouette</span><h2 className="serif">The wardrobe, reimagined</h2></div></div><div className="category-grid">{categories.map(category => <Link href={`/collections/${category.slug}`} className="category-card" key={category.slug}><FashionPlaceholder label={category.name} tone={category.tone}/><h3>{category.name} →</h3></Link>)}</div></section>
<section id="new-arrivals" className="section container"><div className="section-heading"><div><span className="eyebrow">The first edit · Preview</span><h2 className="serif">A closer look</h2></div><Link className="text-link" href="/shop">Explore all styles</Link></div><div className="catalog-grid">{featured.map(product => <CatalogCard key={product.slug} product={product}/>)}</div></section>
<section id="occasions" className="section container"><div className="section-heading"><div><span className="eyebrow">A reason to dress up</span><h2 className="serif">Every kind of day</h2></div></div><div className="occasion-grid">{occasions.map(item => <div className="occasion-card" key={item.name}><FashionPlaceholder label={`${item.name} concept`} tone={item.tone}/><h3>{item.name}</h3></div>)}</div></section>
<section className="section container"><div className="section-heading"><div><span className="eyebrow">The moodboard</span><h2 className="serif">Trending ideas</h2></div></div><div className="mini-grid">{["Quiet details","The art of layering","A softer palette"].map((title,i) => <article className="mini-card" key={title}><span className="eyebrow">0{i+1} / Style note</span><h3>{title}</h3><p className="muted">An original point of view on contemporary Indian dressing.</p></article>)}</div></section>
<section id="best-sellers" className="section container"><div className="section-heading"><div><span className="eyebrow">A first look</span><h2 className="serif">Future favourites</h2></div></div><p className="notice">Sales rankings will appear after verified orders. Our current catalogue is a preview; purchases are not yet available.</p></section>
<section id="editorial" className="editorial"><FashionPlaceholder label="The AURELIA story" tone="sand"/><div className="editorial-copy"><span className="eyebrow">The point of view</span><h2 className="serif">Tradition, with room to move.</h2><p>Inspired by the changing rhythms of everyday life, AURELIA brings a fresh perspective to Indian occasionwear and the pieces you reach for in between.</p><a className="text-link" href="#journal">Explore our style notes</a></div></section>
<section className="section container"><div className="section-heading"><div><span className="eyebrow">The palette</span><h2 className="serif">Choose your mood</h2></div></div><div className="color-grid">{[{name:"Warm ivory",color:"#e7d8c3"},{name:"Earth rose",color:"#b68a80"},{name:"Olive",color:"#859073"},{name:"Dusty blue",color:"#809aaa"},{name:"Clay",color:"#af8068"}].map(item => <div className="color-swatch" key={item.name}><span style={{background:item.color}}/>{item.name}</div>)}</div></section>
<section className="section container"><div className="editorial"><div className="editorial-copy"><span className="eyebrow">Imagery, your way</span><h2 className="serif">See the whole look.</h2><p>Future product pages will pair original garment images with optional AI-assisted styling imagery. Garment fidelity and transparent labeling matter.</p><p className="muted">AI image generation is not enabled in this phase.</p></div><FashionPlaceholder label="AI styling preview placeholder" tone="blue"/></div></section>
<section className="section container"><div className="section-heading"><div><span className="eyebrow">Your voice</span><h2 className="serif">Reviews worth sharing</h2></div></div><p className="notice">Verified customer reviews will appear after real orders are available. We do not publish invented testimonials.</p></section>
<section id="journal" className="section container"><div className="section-heading"><div><span className="eyebrow">The journal</span><h2 className="serif">Ideas to wear</h2></div></div><div className="mini-grid">{["A wardrobe that moves with you","Small details, lasting impressions","The many moods of occasionwear"].map((title,i) => <article className="mini-card" key={title}><span className="eyebrow">Editorial / 0{i+1}</span><h3>{title}</h3><p className="muted">Original editorial stories are coming in a later phase.</p></article>)}</div></section>
<section id="stores" className="section container"><div className="editorial"><FashionPlaceholder label="Visit AURELIA preview" tone="olive"/><div className="editorial-copy"><span className="eyebrow">Beyond the screen</span><h2 className="serif">Meet us, eventually.</h2><p>A store finder is planned. No physical AURELIA locations are listed until verified.</p></div></div></section>
<section id="newsletter" className="newsletter"><span className="eyebrow">Stay in the know</span><h2 className="serif">A little more AURELIA.</h2><p>Newsletter sign-up will be available when email delivery is configured. We won’t collect addresses before then.</p></section>
</main>;}
