"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Menu, X, Search, UserRound, Heart, ShoppingBag } from "lucide-react";
import { AnnouncementBar } from "./announcement-bar";
import { usePreviewStore } from "./preview-store";
const women = [{label:"Kurtas",href:"/collections/kurtas"},{label:"Kurta Sets",href:"/collections/kurta-sets"},{label:"Suits",href:"/collections/suits"},{label:"Dresses",href:"/collections/dresses"},{label:"Sarees",href:"/collections/sarees"},{label:"Lehengas",href:"/collections/lehengas"},{label:"Bottom Wear",href:"/collections/bottom-wear"},{label:"Co-ords",href:"/collections/co-ord-sets"},{label:"Dupattas",href:"/collections/dupattas"}];
const collections = [{label:"All styles",href:"/shop"},{label:"Festive ideas",href:"/#occasions"},{label:"Wedding ideas",href:"/#occasions"},{label:"Workwear ideas",href:"/#occasions"}];
function NavMenu({ label, items }: { label:string; items: typeof women }) { const [open,setOpen]=useState(false); return <div className="mega-wrap" onMouseEnter={() => setOpen(true)} onMouseLeave={() => setOpen(false)} onBlur={e => { if(!e.currentTarget.contains(e.relatedTarget)) setOpen(false); }}><button type="button" aria-expanded={open} aria-haspopup="true" onClick={() => setOpen(!open)} onKeyDown={e => { if(e.key === "Escape") setOpen(false); }}>{label}</button>{open && <div className="mega-menu">{items.map(item => <Link key={item.label} href={item.href} onClick={() => setOpen(false)}>{item.label}</Link>)}</div>}</div>; }
export function SiteHeader() { const [menuOpen,setMenuOpen]=useState(false); const [scrolled,setScrolled]=useState(false); const { ready, state } = usePreviewStore(); useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 10); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []); const wishlistCount = ready ? state.wishlist.length : 0; const bagCount = ready ? state.bag.reduce((sum, item) => sum + item.quantity, 0) : 0; return <header className={`site-header${scrolled ? " scrolled" : ""}`}><AnnouncementBar /><div className="container nav-row"><button className="menu-toggle" type="button" aria-label={menuOpen ? "Close menu":"Open menu"} aria-expanded={menuOpen} aria-controls="mobile-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22}/> : <Menu size={22}/>}</button><Link className="brand" href="/" aria-label="AURELIA home">AURELIA</Link><nav className="nav-links" aria-label="Main navigation"><NavMenu label="Women" items={women}/><Link href="/shop">Shop All</Link><NavMenu label="Collections" items={collections}/><Link href="/#new-arrivals">New Arrivals</Link><Link href="/#editorial">Our Story</Link></nav><div className="nav-actions"><Link className="icon-btn" href="/shop" aria-label="Explore the catalogue"><Search size={20}/></Link><button className="icon-btn" disabled title="Account arrives in a later phase" aria-label="Account coming soon"><UserRound size={20}/></button><Link className="icon-btn" href="/wishlist" aria-label={`Saved preview styles (${wishlistCount})`}><Heart size={20}/><span className="nav-preview-count">{wishlistCount}</span></Link><Link className="icon-btn" href="/bag" aria-label={`Demo bag (${bagCount} items); checkout disabled`}><ShoppingBag size={20}/><span className="nav-preview-count">{bagCount}</span></Link></div></div>{menuOpen && <nav className="mobile-nav container" id="mobile-navigation" aria-label="Mobile navigation">{[{label:"Shop All",href:"/shop"},...women,...collections,{label:"Saved styles",href:"/wishlist"},{label:"Demo bag",href:"/bag"},{label:"New Arrivals",href:"/#new-arrivals"}].map((item,i) => <Link key={`${item.label}-${i}`} href={item.href} onClick={() => setMenuOpen(false)}>{item.label}</Link>)}</nav>}</header>; }
