export type JournalEntry = { slug: string; title: string; date: string; author: string; summary: string; paragraphs: readonly string[] };

/** Original preview editorial; dates are editorial labels, not claims about published merchandise. */
export const journalEntries: readonly JournalEntry[] = [
  { slug: "wardrobe-that-moves", title: "A wardrobe that moves with you", date: "2026-09-27", author: "AURELIA editorial", summary: "A note on building a wardrobe around the changing shape of a day.", paragraphs: ["A day can begin with a quiet morning and end with a celebration. The pieces we return to often make room for both: familiar shapes, comfortable layers and details that feel like our own.", "Think of the edit as a collection of ideas, not a set of rules. A kurta can be layered, dressed up, or kept simple. The most useful wardrobe is one that still feels like you.", "The styles shown on this site are concepts. Materials, fit and availability will be verified before anything is offered for sale."] },
  { slug: "small-details", title: "Small details, lasting impressions", date: "2026-09-27", author: "AURELIA editorial", summary: "How a colour, texture or layer can change the mood of an outfit.", paragraphs: ["Sometimes the smallest choice sets the tone: a soft colour beside a deep one, a lightly structured layer, or a considered finishing detail.", "Use colour to discover ideas rather than prescribe an occasion. Pair what feels interesting, then edit until the combination feels effortless.", "Our illustrations are mood studies, not photographs of finished garments. Product specifications will come after verification."] },
  { slug: "moods-of-occasionwear", title: "The many moods of occasionwear", date: "2026-09-27", author: "AURELIA editorial", summary: "Celebration can look different for everyone.", paragraphs: ["Occasionwear need not follow a single formula. Some days call for a generous silhouette; others call for a small touch of ceremony in an everyday look.", "The best starting point is the event itself and the way you want to move through it. Colour, shape and layering can help tell your own story.", "These are editorial inspirations only. No garment on this preview is currently available for purchase."] },
];
export const findJournalEntry = (slug: string) => journalEntries.find(entry => entry.slug === slug);
